/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppVariaveisRouteImport } from './routes/_app.variaveis'
import { Route as AppTestesRouteImport } from './routes/_app.testes'
import { Route as AppMemoriaRouteImport } from './routes/_app.memoria'
import { Route as AppLogsRouteImport } from './routes/_app.logs'
import { Route as AppImplantacaoRouteImport } from './routes/_app.implantacao'
import { Route as AppFlowRouteImport } from './routes/_app.flow'
import { Route as AppFerramentasRouteImport } from './routes/_app.ferramentas'
import { Route as AppConsumoRouteImport } from './routes/_app.consumo'
import { Route as AppConhecimentoRouteImport } from './routes/_app.conhecimento'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppCanaisRouteImport } from './routes/_app.canais'
import { Route as AppAppsIndexRouteImport } from './routes/_app.apps.index'
import { Route as AppAgentesIndexRouteImport } from './routes/_app.agentes.index'
import { Route as AppAppsGoogleCalendarRouteImport } from './routes/_app.apps.google-calendar'
import { Route as AppAgentesNovoRouteImport } from './routes/_app.agentes.novo'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVariaveisRoute = AppVariaveisRouteImport.update({
  id: '/variaveis',
  path: '/variaveis',
  getParentRoute: () => AppRoute,
} as any)
const AppTestesRoute = AppTestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriaRoute = AppMemoriaRouteImport.update({
  id: '/memoria',
  path: '/memoria',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppImplantacaoRoute = AppImplantacaoRouteImport.update({
  id: '/implantacao',
  path: '/implantacao',
  getParentRoute: () => AppRoute,
} as any)
const AppFlowRoute = AppFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => AppRoute,
} as any)
const AppFerramentasRoute = AppFerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => AppRoute,
} as any)
const AppConsumoRoute = AppConsumoRouteImport.update({
  id: '/consumo',
  path: '/consumo',
  getParentRoute: () => AppRoute,
} as any)
const AppConhecimentoRoute = AppConhecimentoRouteImport.update({
  id: '/conhecimento',
  path: '/conhecimento',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCanaisRoute = AppCanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsIndexRoute = AppAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesIndexRoute = AppAgentesIndexRouteImport.update({
  id: '/agentes/',
  path: '/agentes/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppsGoogleCalendarRoute = AppAppsGoogleCalendarRouteImport.update({
  id: '/apps/google-calendar',
  path: '/apps/google-calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentesNovoRoute = AppAgentesNovoRouteImport.update({
  id: '/agentes/novo',
  path: '/agentes/novo',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/canais': typeof AppCanaisRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conhecimento': typeof AppConhecimentoRoute
  '/consumo': typeof AppConsumoRoute
  '/ferramentas': typeof AppFerramentasRoute
  '/flow': typeof AppFlowRoute
  '/implantacao': typeof AppImplantacaoRoute
  '/logs': typeof AppLogsRoute
  '/memoria': typeof AppMemoriaRoute
  '/testes': typeof AppTestesRoute
  '/variaveis': typeof AppVariaveisRoute
  '/agentes/novo': typeof AppAgentesNovoRoute
  '/apps/google-calendar': typeof AppAppsGoogleCalendarRoute
  '/agentes/': typeof AppAgentesIndexRoute
  '/apps/': typeof AppAppsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/canais': typeof AppCanaisRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/conhecimento': typeof AppConhecimentoRoute
  '/consumo': typeof AppConsumoRoute
  '/ferramentas': typeof AppFerramentasRoute
  '/flow': typeof AppFlowRoute
  '/implantacao': typeof AppImplantacaoRoute
  '/logs': typeof AppLogsRoute
  '/memoria': typeof AppMemoriaRoute
  '/testes': typeof AppTestesRoute
  '/variaveis': typeof AppVariaveisRoute
  '/': typeof AppIndexRoute
  '/agentes/novo': typeof AppAgentesNovoRoute
  '/apps/google-calendar': typeof AppAppsGoogleCalendarRoute
  '/agentes': typeof AppAgentesIndexRoute
  '/apps': typeof AppAppsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/canais': typeof AppCanaisRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/conhecimento': typeof AppConhecimentoRoute
  '/_app/consumo': typeof AppConsumoRoute
  '/_app/ferramentas': typeof AppFerramentasRoute
  '/_app/flow': typeof AppFlowRoute
  '/_app/implantacao': typeof AppImplantacaoRoute
  '/_app/logs': typeof AppLogsRoute
  '/_app/memoria': typeof AppMemoriaRoute
  '/_app/testes': typeof AppTestesRoute
  '/_app/variaveis': typeof AppVariaveisRoute
  '/_app/': typeof AppIndexRoute
  '/_app/agentes/novo': typeof AppAgentesNovoRoute
  '/_app/apps/google-calendar': typeof AppAppsGoogleCalendarRoute
  '/_app/agentes/': typeof AppAgentesIndexRoute
  '/_app/apps/': typeof AppAppsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/canais'
    | '/configuracoes'
    | '/conhecimento'
    | '/consumo'
    | '/ferramentas'
    | '/flow'
    | '/implantacao'
    | '/logs'
    | '/memoria'
    | '/testes'
    | '/variaveis'
    | '/agentes/novo'
    | '/apps/google-calendar'
    | '/agentes/'
    | '/apps/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/canais'
    | '/configuracoes'
    | '/conhecimento'
    | '/consumo'
    | '/ferramentas'
    | '/flow'
    | '/implantacao'
    | '/logs'
    | '/memoria'
    | '/testes'
    | '/variaveis'
    | '/'
    | '/agentes/novo'
    | '/apps/google-calendar'
    | '/agentes'
    | '/apps'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/canais'
    | '/_app/configuracoes'
    | '/_app/conhecimento'
    | '/_app/consumo'
    | '/_app/ferramentas'
    | '/_app/flow'
    | '/_app/implantacao'
    | '/_app/logs'
    | '/_app/memoria'
    | '/_app/testes'
    | '/_app/variaveis'
    | '/_app/'
    | '/_app/agentes/novo'
    | '/_app/apps/google-calendar'
    | '/_app/agentes/'
    | '/_app/apps/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/variaveis': {
      id: '/_app/variaveis'
      path: '/variaveis'
      fullPath: '/variaveis'
      preLoaderRoute: typeof AppVariaveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/testes': {
      id: '/_app/testes'
      path: '/testes'
      fullPath: '/testes'
      preLoaderRoute: typeof AppTestesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memoria': {
      id: '/_app/memoria'
      path: '/memoria'
      fullPath: '/memoria'
      preLoaderRoute: typeof AppMemoriaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logs': {
      id: '/_app/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/implantacao': {
      id: '/_app/implantacao'
      path: '/implantacao'
      fullPath: '/implantacao'
      preLoaderRoute: typeof AppImplantacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flow': {
      id: '/_app/flow'
      path: '/flow'
      fullPath: '/flow'
      preLoaderRoute: typeof AppFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ferramentas': {
      id: '/_app/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof AppFerramentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consumo': {
      id: '/_app/consumo'
      path: '/consumo'
      fullPath: '/consumo'
      preLoaderRoute: typeof AppConsumoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conhecimento': {
      id: '/_app/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof AppConhecimentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/canais': {
      id: '/_app/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof AppCanaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/': {
      id: '/_app/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppAppsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agentes/': {
      id: '/_app/agentes/'
      path: '/agentes'
      fullPath: '/agentes/'
      preLoaderRoute: typeof AppAgentesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/apps/google-calendar': {
      id: '/_app/apps/google-calendar'
      path: '/apps/google-calendar'
      fullPath: '/apps/google-calendar'
      preLoaderRoute: typeof AppAppsGoogleCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agentes/novo': {
      id: '/_app/agentes/novo'
      path: '/agentes/novo'
      fullPath: '/agentes/novo'
      preLoaderRoute: typeof AppAgentesNovoRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCanaisRoute: typeof AppCanaisRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppConhecimentoRoute: typeof AppConhecimentoRoute
  AppConsumoRoute: typeof AppConsumoRoute
  AppFerramentasRoute: typeof AppFerramentasRoute
  AppFlowRoute: typeof AppFlowRoute
  AppImplantacaoRoute: typeof AppImplantacaoRoute
  AppLogsRoute: typeof AppLogsRoute
  AppMemoriaRoute: typeof AppMemoriaRoute
  AppTestesRoute: typeof AppTestesRoute
  AppVariaveisRoute: typeof AppVariaveisRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAgentesNovoRoute: typeof AppAgentesNovoRoute
  AppAppsGoogleCalendarRoute: typeof AppAppsGoogleCalendarRoute
  AppAgentesIndexRoute: typeof AppAgentesIndexRoute
  AppAppsIndexRoute: typeof AppAppsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCanaisRoute: AppCanaisRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppConhecimentoRoute: AppConhecimentoRoute,
  AppConsumoRoute: AppConsumoRoute,
  AppFerramentasRoute: AppFerramentasRoute,
  AppFlowRoute: AppFlowRoute,
  AppImplantacaoRoute: AppImplantacaoRoute,
  AppLogsRoute: AppLogsRoute,
  AppMemoriaRoute: AppMemoriaRoute,
  AppTestesRoute: AppTestesRoute,
  AppVariaveisRoute: AppVariaveisRoute,
  AppIndexRoute: AppIndexRoute,
  AppAgentesNovoRoute: AppAgentesNovoRoute,
  AppAppsGoogleCalendarRoute: AppAppsGoogleCalendarRoute,
  AppAgentesIndexRoute: AppAgentesIndexRoute,
  AppAppsIndexRoute: AppAppsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
